# Generated by Django 3.0.5 on 2020-08-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_titles_genres_categories', '0002_auto_20200821_0056'),
        ('api_comments_reviews', '0003_auto_20200809_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api_titles_genres_categories.Title'),
        ),
    ]
