version: "3.8"

volumes:
  postgres_data:
  static_volume:


services:
  db:
    image: postgres:latest # без тега latest не проходит тесты
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: raikirixd/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web