version: "3.8"

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    image: raikirixd/yamdb_final:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  web:
    build: ./nginx
    volumes:
      - static:/home/code/static
    ports:
    - '80:80'
    depends_on:
      - app