# Generated by Django 3.0.5 on 2020-08-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_comments_reviews', '0004_auto_20200821_0056'),
        ('api_titles_genres_categories', '0002_auto_20200821_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titles',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='api_titles_genres_categories.Category'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='api_titles_genres_categories.Genre'),
        ),
    ]
